# @package _group_
_target_: mbrl.models.DeepKoopman
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
act_size: ???
enc_size: 12
hid_size: 200
ensemble_size: 8
propagation_method: random_model
learn_logvar_bounds: false  # so far this works better

activation_fn_cfg:
  _target_: torch.nn.SiLU